[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.start]
cmd = "java -jar target/cosmetics-ecommerce-0.0.1-SNAPSHOT.jar --spring.profiles.active=railway"